import type { Metadata } from "next";
import "./globals.css";
import ModalProvider from "@/components/providers/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <main className="mx-auto max-w-7xl">
          <ModalProvider>{children}</ModalProvider>
        </main>
      </body>
    </html>
  );
}
